### PR TITLE
Refactor django.conf.settings access

### PR DESCRIPTION
**Pull request by lucernae**
Properly access django settings.
Useful for modularity.

### CODE REVIEW

**Comment by lucernae** [comment]
please review @ismailsunni

**Comment by ismailsunni** [comment]
LGTM

**Comment by senoadiw** [comment]
Hello, it looks like the package @ https://pypi.python.org/pypi/geonode_qgis_server needs updating since it still calls from geonode.settings import QGIS_SERVER_CONFIG

This causes geonode_qgis_server to break GeoNode that uses a custom settings file like my_geonode.settings.

Cheers

**Comment by timlinux** [comment]
Hi @senoadiw 

Maybe it is better to file a fresh ticket as I fear your comment will get buried here in the comments of a closed pull request.

@ismailsunni can you investigate the query above?

**Pull request merged**
